In [1]:
import pandas as pd
import numpy as np

In [2]:
df_death_rates = pd.read_csv('../data/Air-pollution/death-rates-from-air-pollution.csv')
df_death_rates

,Entity,Code,Year,Deaths - Cause: All causes - Risk: Household air pollution from solid fuels - Sex: Both - Age: Age-standardized (Rate),Deaths - Cause: All causes - Risk: Ambient particulate matter pollution - Sex: Both - Age: Age-standardized (Rate),Deaths - Cause: All causes - Risk: Air pollution - Sex: Both - Age: Age-standardized (Rate),Deaths - Cause: All causes - Risk: Ambient ozone pollution - Sex: Both - Age: Age-standardized (Rate)
0,Afghanistan,AFG,1990,370.050474,30.822693,402.175651,6.581093
1,Afghanistan,AFG,1991,358.978418,29.826184,390.085258,6.267613
2,Afghanistan,AFG,1992,352.766453,29.202030,383.201196,5.926444
3,Afghanistan,AFG,1993,357.055923,29.429702,387.704919,5.860345
4,Afghanistan,AFG,1994,362.970439,29.813259,394.022027,6.065343
...,...,...,...,...,...,...,...
6835,Zimbabwe,ZWE,2015,143.477957,38.996842,183.044625,1.091220
6836,Zimbabwe,ZWE,2016,140.643245,37.585998,179.060638,1.231540
6837,Zimbabwe,ZWE,2017,137.448374,35.811023,174.048806,1.447558
6838,Zimbabwe,ZWE,2018,133.923031,34.932825,169.534057,1.407389
6839,Zimbabwe,ZWE,2019,130.508301,34.404599,165.724397,1.435934